title:        'BlahGeek'
tagline:      "BlahGeek's Blog"
name:         "BlahGeek's Blog"
url:          "http://blog.blahgeek.com"

# markdown:     rdiscount
exclude:      ['makefile']

author:
  name: BlahGeek
  email: 'i@BlahGeek.com'

markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "underline", "footnotes"]

permalink:    pretty
pygments:     true
paginate:     5
disqus:       blahgeekblog

google_analytics: 'UA-37086826-2'
